import { Doctor } from '@/types/doctor.types';

export const doctorsData: Doctor[] = [
  {
    id: 'dr-arjun-jawahar-sharma',
    name: 'Dr. Arjun Jawahar Sharma',
    title: 'Specialist in: Dentures, Crowns & Implants',
    specialty: 'BDS, MDS (Prosthodontics & Oral Implantologist)',
    degrees: [
      'BDS, MDS (Prosthodontics & Oral Implantologist)',
      'MBA (AMIS; IIB)',
    ],
    experienceYears: 15,
    bio: 'BDS, MDS (Prosthodontics & Oral Implantologist), MBA (AMIS; IIB). Specialist in: Dentures, Crowns & Implants. Ex-Consultant - Clove Dental. Faculty - K.D. Dental College & Hospital.',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=800&auto=format&fit=crop',
    achievements: [
      'BDS, MDS (Prosthodontics & Oral Implantologist)',
      'MBA (AMIS; IIB)',
      'Specialist in: Dentures, Crowns & Implants',
      'Ex-Consultant - Clove Dental',
      'Faculty - K.D. Dental College & Hospital',
    ],
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-priyanka-sharma',
    name: 'Dr. Priyanka Sharma',
    title: 'Certified Endodontist & Dental Surgeon',
    specialty: 'BDS, (Dental Surgeon)',
    degrees: [
      'BDS, (Dental Surgeon)',
      'Certified Endodontist',
    ],
    experienceYears: 12,
    bio: 'BDS, (Dental Surgeon), Certified Endodontist. Member Indian Dental Association. Ex-Consultant - Sri Ganga Ram Hospital, New Delhi. Ex-Lecturer - ITS Dental College & Hospitals.',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-78a9c2b4c107?q=80&w=800&auto=format&fit=crop',
    achievements: [
      'BDS, (Dental Surgeon)',
      'Certified Endodontist',
      'Member Indian Dental Association',
      'Ex-Consultant - Sri Ganga Ram Hospital, New Delhi',
      'Ex-Lecturer - ITS Dental College & Hospitals',
    ],
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-sandeep',
    name: 'Dr. Sandeep',
    title: 'Dental Surgeon & Endodontic Specialist',
    specialty: 'BDS (Dental Surgeon)',
    degrees: [
      'BDS (Dental Surgeon)',
      'Root Canal & Restorative Specialist',
    ],
    experienceYears: 10,
    bio: 'BDS (Dental Surgeon). Specialist in Root Canal Treatment (RCT), tooth fillings, and pain-free restorative dental procedures with gentle care.',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=800&auto=format&fit=crop',
    achievements: [
      'BDS (Dental Surgeon)',
      'Specialist in Single-Seating RCT & Tooth Fillings',
      'Member Indian Dental Association',
    ],
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-vikrant',
    name: 'Dr. Vikrant',
    title: 'Dental Surgeon & Clinical Diagnostics',
    specialty: 'BDS (Dental Surgeon)',
    degrees: [
      'BDS (Dental Surgeon)',
      'Oral Diagnostics & Extractions',
    ],
    experienceYears: 11,
    bio: 'BDS (Dental Surgeon). Specialist in clinical oral diagnostics, atraumatic tooth extractions, and comprehensive oral surgery care.',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=800&auto=format&fit=crop',
    achievements: [
      'BDS (Dental Surgeon)',
      'Specialist in Clinical Extractions & Digital Diagnostics',
      'Member Indian Dental Association',
    ],
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-rajwinder-kaur',
    name: 'Dr. Rajwinder Kaur',
    title: 'Dental Surgeon & Restorative Care',
    specialty: 'BDS (Dental Surgeon)',
    degrees: [
      'BDS (Dental Surgeon)',
      'Restorative & Cosmetic Care',
    ],
    experienceYears: 9,
    bio: 'BDS (Dental Surgeon). Dedicated specialist in aesthetic tooth restorations, preventative care, and patient-centered dental treatments.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop',
    achievements: [
      'BDS (Dental Surgeon)',
      'Specialist in Restorative & Family Dentistry',
      'Member Indian Dental Association',
    ],
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
];
