import { Doctor } from '@/types/doctor.types';

export const doctorsData: Doctor[] = [
  {
    id: 'dr-arjun-jawahar-sharma',
    name: 'Dr. Arjun Jawahar Sharma',
    title: 'Prosthodontist & Oral Implantologist',
    specialty: 'BDS, MDS | MBA (ISB) | Fellow, AOI & ICOI',
    degrees: [
      'BDS, MDS (Prosthodontist & Oral Implantologist)',
      'MBA, Indian School of Business (ISB)',
      'Fellow, Academy of Oral Implantology (AOI)',
      'Fellow, International Congress of Oral Implantologists (ICOI)',
    ],
    experienceYears: 14,
    about: 'Dr. Arjun Jawahar Sharma, BDS, MDS, is a highly experienced Prosthodontist and Oral Implantologist with more than 14 years of clinical experience and expertise in advanced implant dentistry and comprehensive oral rehabilitation. With 10,000+ implant placements, he has extensive experience in treating complex cases involving missing teeth, failing dentition, extensive tooth loss, and full-mouth rehabilitation.',
    bio: 'Highly experienced Prosthodontist & Oral Implantologist with 14+ years of clinical excellence and 10,000+ implant placements specializing in complex full-mouth rehabilitation.',
    avatarUrl: '/doctors/dr-arjun-jawahar-sharma.svg',
    achievements: [
      '14+ Years Clinical Experience & 10,000+ Dental Implants Placed',
      'MBA from Indian School of Business (ISB)',
      'Fellow, Academy of Oral Implantology (AOI)',
      'Fellow, International Congress of Oral Implantologists (ICOI)',
      'Member, Indian Dental Association (IDA) & Digital Dentistry Forum',
      'Specialist in Computer-Guided Implantology & Full-Mouth Rehabilitation',
    ],
    expertiseSections: [
      {
        title: 'Expertise in Prosthodontics',
        description: 'As a Prosthodontist, Dr. Sharma specialises in restoring and replacing teeth while maintaining harmony between function, aesthetics, bite, facial appearance, and long-term oral health. His expertise includes dental implants, crowns and bridges, veneers, implant-supported teeth, complete and partial dentures, full-mouth rehabilitation, aesthetic dentistry, and complex restorative treatments.',
      },
      {
        title: 'Expertise in Implant Dentistry',
        description: 'As an experienced Oral Implantologist, Dr. Sharma provides comprehensive implant treatment ranging from single-tooth implants and multiple implant restorations to full-arch and full-mouth implant rehabilitation. His approach combines precise implant placement with carefully planned prosthetic rehabilitation, ensuring that the final teeth are designed to look natural and function comfortably.',
      },
      {
        title: 'Full-Mouth Rehabilitation & Digital Dentistry',
        description: 'Dr. Sharma has a particular interest in complex full-mouth rehabilitation, where multiple dental problems are addressed as part of one comprehensive treatment plan. He also incorporates digital dentistry and technology-driven treatment planning, including 3D imaging, digital impressions, computer-guided implant planning, digitally designed restorations, CAD/CAM technology, and digitally assisted rehabilitation where appropriate.',
      },
    ],
    educationCredentials: [
      'BDS, MDS in Prosthodontics & Oral Implantology',
      'MBA – Indian School of Business (ISB)',
      'Fellow of the Academy of Oral Implantology (AOI)',
      'Fellow of the International Congress of Oral Implantologists (ICOI)',
      'Member – Indian Dental Association (IDA)',
      'Member – Academy of Oral Implantology (AOI)',
      'Member – Digital Dentistry Forum',
    ],
    clinicalPhilosophy: "His clinical philosophy is centred on comprehensive diagnosis, evidence-based treatment planning, precision, aesthetics, and long-term function. His goal is to restore a patient's ability to eat, speak, smile, and live with confidence through predictable and personalised dental rehabilitation.",
    statsTagline: '14+ Years of Clinical Experience | 10,000+ Implant Placements | Prosthodontics | Oral Implantology | Full-Mouth Rehabilitation | Digital Dentistry',
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-priyanka-sharma',
    name: 'Dr. Priyanka Sharma',
    title: 'General & Restorative Dentist | Root Canal Specialist',
    specialty: 'BDS | Root Canal & Rehabilitation Specialist',
    degrees: [
      'BDS (Bachelor of Dental Surgery)',
      'General & Restorative Dentist',
      'Root Canal & Rehabilitation Specialist',
      'Ex-Junior Resident, Sir Ganga Ram Hospital, New Delhi',
    ],
    experienceYears: 11,
    about: 'Dr. Priyanka Sharma, BDS, is an experienced dental professional with over 11 years of clinical experience, specialising in root canal treatment, restorative dentistry, crowns, and comprehensive dental rehabilitation. She has successfully performed 20,000+ root canal treatments (RCTs), along with extensive experience in crowns and multiple full-mouth rehabilitation cases.',
    bio: 'Experienced dental surgeon with over 11 years of clinical experience and 20,000+ successful root canal treatments, focusing on tooth preservation and patient comfort.',
    avatarUrl: '/doctors/dr-priyanka-sharma.svg',
    achievements: [
      '11+ Years Clinical Experience & 20,000+ Successful Root Canal Treatments (RCTs)',
      'Ex-Junior Resident at Sir Ganga Ram Hospital, New Delhi',
      'Ex-Department of Endodontics, New Delhi',
      'Specialist in Crowns, Tooth-Coloured Restorations & Bite Reconstruction',
      'Member, Indian Dental Association (IDA)',
      'Specialist in Pain-Free Single-Seating Root Canal Therapy',
    ],
    expertiseSections: [
      {
        title: 'Clinical Training & Experience',
        description: 'Dr. Priyanka Sharma has gained valuable clinical experience through her tenure as a Junior Resident at Sir Ganga Ram Hospital, New Delhi, and in the Department of Endodontics in Delhi. This experience has helped develop a strong foundation in the diagnosis and management of dental diseases affecting teeth and their supporting structures.',
      },
      {
        title: 'Expertise in Root Canal Treatment',
        description: 'With extensive experience in endodontic treatment, Dr. Priyanka Sharma focuses on preserving natural teeth whenever possible. Her approach emphasises accurate diagnosis, meticulous canal cleaning and shaping, pain management, and durable restoration of the treated tooth.',
      },
      {
        title: 'Crowns & Restorative Dentistry',
        description: 'Dr. Priyanka Sharma has extensive experience in restoring teeth that are structurally weakened, heavily restored, fractured, or treated with root canal therapy. She provides comprehensive restorative solutions including dental crowns and tooth-coloured restorations designed to restore strength, function, appearance, and long-term stability.',
      },
      {
        title: 'Full-Mouth Rehabilitation',
        description: 'Dr. Priyanka Sharma has been involved in multiple full-mouth rehabilitation cases, where several dental problems are addressed through one comprehensive treatment plan. Such rehabilitation may involve root canal treatments, crowns, restorations, replacement of missing teeth, bite correction, and aesthetic rehabilitation.',
      },
    ],
    educationCredentials: [
      'BDS – Bachelor of Dental Surgery',
      'Tenure as Junior Resident – Sir Ganga Ram Hospital, New Delhi',
      'Tenure in Department of Endodontics – New Delhi',
      'Member – Indian Dental Association (IDA)',
    ],
    clinicalPhilosophy: 'She believes in providing treatment that combines clinical precision with patient comfort. Her approach is centred around careful diagnosis, transparent treatment planning, preservation of natural teeth, and long-term restorative outcomes.',
    statsTagline: '11+ Years of Clinical Experience | 20,000+ RCTs | Crowns & Restorative Dentistry | Full-Mouth Rehabilitation | Endodontic Care',
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-sandeep-kaur',
    name: 'Dr. Sandeep Kaur',
    title: 'Junior Associate Dentist | Comprehensive General Dentistry',
    specialty: 'BDS | Comprehensive General Dentistry',
    degrees: [
      'BDS – Dental College, Patiala',
      'Junior Associate Dentist',
      'Comprehensive General Dentistry',
    ],
    experienceYears: 7,
    about: 'Dr. Sandeep Kaur, BDS, is an experienced dental professional with 7 years of clinical experience, dedicated to providing comprehensive and patient-focused dental care. She completed her Bachelor of Dental Surgery (BDS) from Dental College, Patiala.',
    bio: 'Dedicated dental surgeon with 7 years of clinical experience, including 5 years of association with Jawahar Dental Hospital in preventive, restorative, and periodontal care.',
    avatarUrl: '/doctors/dr-sandeep-kaur.svg',
    achievements: [
      '7+ Years of Clinical Experience in General & Restorative Dentistry',
      '5 Years of dedicated association with Jawahar Dental Hospital',
      'BDS from Dental College, Patiala',
      'Specialist in Aesthetic Fillings, Periodontal Care & Dental Crowns',
      'Member, Indian Dental Association (IDA)',
      'Patient-Focused & Gentle Dental Care Approach',
    ],
    expertiseSections: [
      {
        title: 'Clinical Experience',
        description: 'Dr. Sandeep Kaur has been associated with Jawahar Dental Hospital for the past 5 years as a Junior Associate Dentist, where she has gained significant hands-on experience in the diagnosis, treatment, and management of a diverse range of dental conditions.',
      },
      {
        title: 'Comprehensive Dental Procedures',
        description: 'Over the course of her clinical practice, Dr. Sandeep Kaur has developed extensive hands-on experience across a wide range of dental procedures. Her clinical exposure includes general dentistry, restorative procedures, dental fillings, preventive dental care, basic oral surgical procedures, crowns and bridges, periodontal care, and comprehensive dental treatments as required.',
      },
      {
        title: 'Commitment to Quality Care',
        description: 'With 7 years of clinical experience, including 5 years of dedicated association with Jawahar Dental Hospital, Dr. Sandeep Kaur continues to contribute to comprehensive dental care and works closely with the clinical team to provide coordinated treatment.',
      },
    ],
    educationCredentials: [
      'BDS – Bachelor of Dental Surgery, Dental College, Patiala',
      '7+ Years of Clinical Practice',
      '5 Years with Jawahar Dental Hospital',
      'Member – Indian Dental Association (IDA)',
    ],
    clinicalPhilosophy: 'Dr. Sandeep Kaur believes that good dentistry begins with understanding the patient and establishing a clear diagnosis and treatment plan. She places strong emphasis on patient education, preventive care, and creating a comfortable dental experience.',
    statsTagline: 'BDS – Dental College, Patiala | 7+ Years of Clinical Experience | 5 Years with Jawahar Dental Hospital | Comprehensive Dental Procedures | Patient-Centred Care',
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-rajwinder-kaur',
    name: 'Dr. Rajwinder Kaur',
    title: 'Junior Associate Dentist | General Dentistry',
    specialty: 'BDS | General & Preventive Dentistry',
    degrees: [
      'BDS – Bachelor of Dental Surgery',
      'Junior Associate Dentist',
      'General & Preventive Care Specialist',
    ],
    experienceYears: 2,
    about: 'Dr. Rajwinder Kaur, BDS, is a dedicated dental professional with 2 years of clinical experience, committed to providing compassionate, comprehensive, and patient-focused dental care.',
    bio: 'Compassionate dental practitioner committed to comfortable patient experience, preventative oral healthcare, and precision restorative treatments.',
    avatarUrl: '/doctors/dr-rajwinder-kaur.svg',
    achievements: [
      '2+ Years of Clinical Experience in General & Preventive Dentistry',
      'Junior Associate Dentist at Jawahar Dental Hospital',
      'Focus on Systematic Diagnosis, Patient Comfort & Oral Health Education',
      'Specialist in Conservative Restorations & Preventative Dental Treatments',
      'Member, Indian Dental Association (IDA)',
    ],
    expertiseSections: [
      {
        title: 'Clinical Experience',
        description: 'Working as a Junior Associate Dentist, Dr. Rajwinder Kaur has gained valuable hands-on clinical exposure across a range of general dental procedures. Her practice focuses on accurate diagnosis, preventive dental care, restorative treatments, and assisting in the management of patients requiring comprehensive dental care.',
      },
      {
        title: 'Clinical Approach & Patient-Centred Care',
        description: 'Dr. Rajwinder Kaur believes in providing dentistry with a strong emphasis on patient comfort, clinical precision, and preventive oral healthcare. She takes time to understand individual patient concerns and follows a systematic approach to diagnosis and treatment. With a caring and approachable personality, Dr. Rajwinder Kaur is committed to creating a comfortable dental experience for her patients. She believes that educating patients about oral health and encouraging regular preventive care are essential for maintaining healthy teeth and gums over the long term.',
      },
      {
        title: 'Continuous Learning',
        description: 'As a Junior Associate Dentist, she continues to expand her clinical knowledge and skills while working alongside experienced dental professionals, with a commitment to continuous learning, ethical practice, and high-quality patient care.',
      },
    ],
    educationCredentials: [
      'BDS – Bachelor of Dental Surgery',
      'Junior Associate Dentist – Jawahar Dental Hospital',
      'Member – Indian Dental Association (IDA)',
    ],
    clinicalPhilosophy: 'She believes that educating patients about oral health and encouraging regular preventive care are essential for maintaining healthy teeth and gums over the long term, with high emphasis on gentle care and comfort.',
    statsTagline: 'BDS | 2+ Years of Clinical Experience | Junior Associate Dentist | General & Preventive Dentistry | Patient-Centred Care',
    consultationFee: 500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
];
