import { ServiceItem } from '@/types/service.types';

export const servicesData: ServiceItem[] = [
  // CATEGORY 1: DENTAL IMPLANTS
  {
    id: 'full-mouth-rehabilitation',
    slug: 'full-mouth-rehabilitation',
    title: 'Full Mouth Rehabilitation',
    category: 'DENTAL IMPLANTS',
    shortDescription: 'Comprehensive full mouth implant reconstruction for total functional and aesthetic restoration.',
    fullDescription: 'Comprehensive full mouth rehabilitation utilizing advanced dental implant technology to restore chewing function, jaw alignment, and natural smile aesthetics.',
    startingPrice: 15000,
    durationMinutes: 120,
    heroImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Crown',
    popular: true,
    features: [
      { title: 'Complete Jaw Restoration', description: 'Restores complete masticatory function and structural stability.' },
      { title: 'Custom Implant Design', description: 'Tailored precisely to your facial anatomy and jaw structure.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Clinical Evaluation', description: 'Comprehensive 3D scan and treatment planning.', duration: '60 Mins' },
      { stepNumber: 2, title: 'Implant Placement', description: 'Precision guided implant placement.', duration: '120 Mins' },
      { stepNumber: 3, title: 'Final Restoration', description: 'Attachment of permanent aesthetic prosthetics.', duration: '90 Mins' },
    ],
    benefits: ['Restores complete chewing power', 'Improves facial symmetry', 'Long-lasting structural stability'],
  },
  {
    id: 'implants-overdentures',
    slug: 'implants-overdentures',
    title: 'Implants Overdentures',
    category: 'DENTAL IMPLANTS',
    shortDescription: 'Implant-supported overdentures offering superior stability and confidence compared to removable dentures.',
    fullDescription: 'Implant-supported overdentures anchored securely by dental implants, providing firm retention, comfort, and natural speech without slippage.',
    startingPrice: 5000,
    durationMinutes: 90,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'Secure Retention', description: 'Eliminates denture movement during eating and speaking.' },
      { title: 'Bone Preservation', description: 'Helps preserve jawbone density and facial contours.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Implant Anchoring', description: 'Placement of supporting dental implants.', duration: '60 Mins' },
      { stepNumber: 2, title: 'Overdenture Fitting', description: 'Custom fabrication and snap-on attachment.', duration: '60 Mins' },
    ],
    benefits: ['Zero slippage or discomfort', 'Enhanced chewing efficiency', 'Natural aesthetic appearance'],
  },
  {
    id: 'single-implant',
    slug: 'single-implant',
    title: 'Single Implant',
    category: 'DENTAL IMPLANTS',
    shortDescription: 'Permanent single tooth replacement with a titanium implant and custom ceramic crown.',
    fullDescription: 'Single tooth implant placement designed to replace missing teeth seamlessly without affecting adjacent healthy tooth structures.',
    startingPrice: 3800,
    durationMinutes: 60,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'Independent Tooth Replacement', description: 'Preserves adjacent natural teeth without grinding crowns.' },
      { title: 'Natural Root Reproduction', description: 'Integrates directly with jawbone for lifelong strength.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Implant Insertion', description: 'Minimally invasive placement of titanium fixture.', duration: '45 Mins' },
      { stepNumber: 2, title: 'Crown Attachment', description: 'Placement of custom ceramic tooth crown.', duration: '45 Mins' },
    ],
    benefits: ['Preserves adjacent teeth', 'Permanent lifelong solution', 'Matches natural enamel color'],
  },

  // CATEGORY 2: PROSTHODONTICS
  {
    id: 'bridges-crowns',
    slug: 'bridges-crowns',
    title: 'Bridges & Crowns',
    category: 'PROSTHODONTICS',
    shortDescription: 'High-strength ceramic bridges and crowns designed to protect damaged teeth and bridge gaps.',
    fullDescription: 'Custom ceramic crowns and multi-unit dental bridges engineered to restore structural integrity, biting power, and smile aesthetics.',
    startingPrice: 1200,
    durationMinutes: 60,
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    popular: true,
    features: [
      { title: 'Custom Ceramic Shades', description: 'Matched precisely to surrounding tooth shades.' },
      { title: 'Durable Protection', description: 'Reinforces weakened or root-canal treated teeth.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Tooth Preparation', description: 'Reshaping tooth and digital impression.', duration: '45 Mins' },
      { stepNumber: 2, title: 'Permanent Cementation', description: 'Bonding of final crown or bridge.', duration: '30 Mins' },
    ],
    benefits: ['Protects fragile teeth', 'Restores natural bite', 'Seamless color match'],
  },
  {
    id: 'complete-dentures',
    slug: 'complete-dentures',
    title: 'Complete Dentures',
    category: 'PROSTHODONTICS',
    shortDescription: 'Custom full-arch complete dentures tailored for comfortable fit and natural appearance.',
    fullDescription: 'Custom fabricated complete dentures replacing full upper or lower arches of missing teeth with individualized tissue contours.',
    startingPrice: 1800,
    durationMinutes: 60,
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    popular: false,
    features: [
      { title: 'Comfortable Anatomical Fit', description: 'Crafted to match individual gum contours.' },
      { title: 'Restores Facial Profile', description: 'Supports lips and cheeks for youthful facial proportion.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Custom Impression', description: 'Detailed mapping of arch anatomy.', duration: '45 Mins' },
      { stepNumber: 2, title: 'Try-in & Delivery', description: 'Bite adjustment and final delivery.', duration: '45 Mins' },
    ],
    benefits: ['Comfortable daily fit', 'Natural appearance', 'Restores facial support'],
  },
  {
    id: 'partial-dentures',
    slug: 'partial-dentures',
    title: 'Partial Dentures',
    category: 'PROSTHODONTICS',
    shortDescription: 'Removable partial dentures designed to fill gaps and prevent tooth shifting.',
    fullDescription: 'Custom removable partial dentures designed to replace multiple missing teeth while clasping securely to remaining natural teeth.',
    startingPrice: 1400,
    durationMinutes: 45,
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    popular: false,
    features: [
      { title: 'Lightweight & Removable', description: 'Easy maintenance and daily cleaning.' },
      { title: 'Prevents Tooth Drift', description: 'Keeps adjacent teeth in proper alignment.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Impression & Framework', description: 'Precision mapping and base creation.', duration: '45 Mins' },
      { stepNumber: 2, title: 'Insertion & Tuning', description: 'Fitting and clasp adjustment.', duration: '30 Mins' },
    ],
    benefits: ['Prevents shifting teeth', 'Economical solution', 'Removable and hygienic'],
  },
  {
    id: 'veneers-laminates',
    slug: 'veneers-laminates',
    title: 'Veneers / Laminates',
    category: 'PROSTHODONTICS',
    shortDescription: 'Ultra-thin ceramic porcelain veneers and laminates for radiant smile transformations.',
    fullDescription: 'Hand-crafted porcelain veneers and ceramic laminates designed to correct gaps, chips, discoloration, and minor misalignments.',
    startingPrice: 2500,
    durationMinutes: 90,
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    popular: true,
    features: [
      { title: 'Minimal Tooth Prep', description: 'Preserves natural enamel with microscopic accuracy.' },
      { title: 'Stain-Impervious Porcelain', description: 'Guarantees long-lasting shade brightness.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Digital Smile Mockup', description: 'Facial analysis & trial mockup.', duration: '60 Mins' },
      { stepNumber: 2, title: 'Micro-Preparation', description: 'Minimal enamel preparation.', duration: '60 Mins' },
      { stepNumber: 3, title: 'Permanent Bonding', description: 'Precision ceramic shell insertion.', duration: '60 Mins' },
    ],
    benefits: ['Flawless aesthetic symmetry', 'Stain resistant', 'Minimal enamel removal'],
  },

  // CATEGORY 3: ORTHODONTICS
  {
    id: 'brackets-braces',
    slug: 'brackets-braces',
    title: 'Brackets & Braces',
    category: 'ORTHODONTICS',
    shortDescription: 'Traditional metallic and ceramic brackets for comprehensive tooth alignment.',
    fullDescription: 'Orthodontic bracket and wire systems engineered for precise tooth movement, overcrowding correction, and bite correction.',
    startingPrice: 3000,
    durationMinutes: 45,
    heroImage: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smile',
    popular: true,
    features: [
      { title: 'Precise Tooth Movement', description: 'Corrects complex crowding and bite misalignments.' },
      { title: 'Ceramic & Metal Options', description: 'Choice of traditional metal or tooth-colored ceramic brackets.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Orthodontic Records', description: 'Diagnostic impressions and X-rays.', duration: '45 Mins' },
      { stepNumber: 2, title: 'Bracket Bonding', description: 'Precision placement of brackets and archwire.', duration: '60 Mins' },
    ],
    benefits: ['Corrects severe crowding', 'Predictable results', 'Durable alignment system'],
  },
  {
    id: 'aligners',
    slug: 'aligners',
    title: 'Aligners',
    category: 'ORTHODONTICS',
    shortDescription: 'Virtually invisible clear aligner therapy for discreet orthodontic correction.',
    fullDescription: 'Custom transparent clear aligners designed with 3D digital planning to straighten teeth comfortably without metal brackets.',
    startingPrice: 4500,
    durationMinutes: 45,
    heroImage: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smile',
    popular: true,
    features: [
      { title: '100% Transparent', description: 'Virtually unnoticeable during daily wear.' },
      { title: 'Removable for Meals', description: 'Allows unrestricted eating and effortless flossing.' },
    ],
    processSteps: [
      { stepNumber: 1, title: '3D Digital Impression', description: 'Impression-free 3D scanning.', duration: '30 Mins' },
      { stepNumber: 2, title: 'Aligner Set Delivery', description: 'Fitting custom aligner tray sets.', duration: '45 Mins' },
    ],
    benefits: ['Virtually invisible', 'Removable convenience', 'Gentle progressive movement'],
  },
  {
    id: 'corrective-appliances',
    slug: 'corrective-appliances',
    title: 'Corrective Appliances',
    category: 'ORTHODONTICS',
    shortDescription: 'Specialized functional appliances designed to guide jaw growth and bite alignment.',
    fullDescription: 'Custom orthodontic appliances engineered to modify jaw relationships, expand arches, and correct deep bites in growing patients.',
    startingPrice: 1500,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smile',
    popular: false,
    features: [
      { title: 'Jaw Growth Guidance', description: 'Guides jaw growth for proper bite relationship.' },
      { title: 'Arch Expansion', description: 'Creates necessary space for crowded teeth.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Appliance Fitting', description: 'Custom fabrication and fitting.', duration: '30 Mins' },
      { stepNumber: 2, title: 'Progress Adjustments', description: 'Periodic clinical monitoring.', duration: '20 Mins' },
    ],
    benefits: ['Prevents future surgical correction', 'Improves facial symmetry', 'Guides healthy jaw development'],
  },

  // CATEGORY 4: ENDODONTICS
  {
    id: 'tooth-color-fillings',
    slug: 'tooth-color-fillings',
    title: 'Tooth Color Fillings',
    category: 'ENDODONTICS',
    shortDescription: 'Aesthetic composite dental restorations matching natural tooth shade.',
    fullDescription: 'Biocompatible composite resin fillings designed to restore decayed or fractured teeth with seamless tooth-colored matching.',
    startingPrice: 350,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'Natural Shade Match', description: 'Blends invisibly with natural tooth enamel.' },
      { title: 'Strong Adhesive Bond', description: 'Binds directly to tooth structure to prevent leaks.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Decay Removal', description: 'Gently removing infected enamel.', duration: '20 Mins' },
      { stepNumber: 2, title: 'Composite Curing', description: 'Layering and light curing composite resin.', duration: '20 Mins' },
    ],
    benefits: ['Mercury-free composite', 'Invisible seamless match', 'Preserves healthy tooth structure'],
  },
  {
    id: 'root-canal-treatment',
    slug: 'root-canal-treatment',
    title: 'Root Canal Treatment (RCT)',
    category: 'ENDODONTICS',
    shortDescription: 'Painless endodontic therapy saving infected or painful teeth.',
    fullDescription: 'Advanced microscopic root canal therapy designed to clean infected pulp tissue, relieve severe toothache, and preserve natural tooth root structure.',
    startingPrice: 800,
    durationMinutes: 60,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'Painless Pain Relief', description: 'Eliminates acute toothache under local anesthesia.' },
      { title: 'Saves Natural Tooth', description: 'Avoids tooth extraction by sealing root canals.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Canal Cleaning', description: 'Disinfecting infected root canals.', duration: '45 Mins' },
      { stepNumber: 2, title: 'Gutta-Percha Sealing', description: 'Permanent bio-inert root filling.', duration: '30 Mins' },
    ],
    benefits: ['Immediate pain relief', 'Saves natural tooth', 'Prevents bone infection'],
  },
  {
    id: 'single-seating-rct',
    slug: 'single-seating-rct',
    title: 'Single Seating RCT',
    category: 'ENDODONTICS',
    shortDescription: 'Rapid single-visit root canal treatment completed in one comfortable session.',
    fullDescription: 'High-precision single-visit root canal treatment utilizing rotary instrumentation and digital apex locators for complete canal sealing in a single visit.',
    startingPrice: 1000,
    durationMinutes: 60,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'Single Visit Convenience', description: 'Completed in a single appointment without multiple visits.' },
      { title: 'Rotary Instrumentation', description: 'Accelerated disinfections with rotary endodontic files.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Complete Endodontic Protocol', description: 'Cleaning, shaping, and sealing root canals in one visit.', duration: '60 Mins' },
    ],
    benefits: ['Saves time', 'Completed in 1 visit', 'High success rate'],
  },
  {
    id: 'post-cores',
    slug: 'post-cores',
    title: 'Post & Cores',
    category: 'ENDODONTICS',
    shortDescription: 'Structural post and core reinforcement for severely broken-down teeth.',
    fullDescription: 'Reinforcement procedure placing a biocompatible post inside a root canal treated tooth to support a full protective crown.',
    startingPrice: 600,
    durationMinutes: 45,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: false,
    features: [
      { title: 'Structural Reinforcement', description: 'Rebuilds heavily decayed tooth foundations.' },
      { title: 'Fiber Post Options', description: 'Esthetic glass fiber posts matching tooth flexibility.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Post Space Prep', description: 'Preparing canal space and cementation.', duration: '30 Mins' },
      { stepNumber: 2, title: 'Core Build-up', description: 'Building tooth core for crown support.', duration: '20 Mins' },
    ],
    benefits: ['Restores severely broken teeth', 'Provides strong crown foundation', 'Long-lasting support'],
  },

  // CATEGORY 5: ORAL & MAXILLOFACIAL SURGERY
  {
    id: 'wisdom-tooth-extraction',
    slug: 'wisdom-tooth-extraction',
    title: 'Wisdom Tooth Extraction',
    category: 'ORAL & MAXILLOFACIAL SURGERY',
    shortDescription: 'Safe, atraumatic extraction of impacted or painful third molars.',
    fullDescription: 'Surgical removal of impacted or wisdom teeth performed under local anesthesia with minimal discomfort and fast healing.',
    startingPrice: 1500,
    durationMinutes: 45,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'Atraumatic Surgical Technique', description: 'Minimizes post-operative swelling and discomfort.' },
      { title: 'Impacted Tooth Removal', description: 'Safely extracts deeply buried or horizontal wisdom teeth.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Anesthesia & Access', description: 'Gentle numbing and flap elevation.', duration: '15 Mins' },
      { stepNumber: 2, title: 'Extraction & Suturing', description: 'Sectioning tooth and placing dissolvable sutures.', duration: '30 Mins' },
    ],
    benefits: ['Relieves crowding pain', 'Prevents cysts and infection', 'Quick recovery protocol'],
  },
  {
    id: 'root-stump-extraction',
    slug: 'root-stump-extraction',
    title: 'Root Stump Extraction',
    category: 'ORAL & MAXILLOFACIAL SURGERY',
    shortDescription: 'Gentle surgical removal of remaining non-restorable tooth root fragments.',
    fullDescription: 'Careful removal of broken root stumps left beneath gum lines to clean underlying infection and prepare sites for healing or implants.',
    startingPrice: 600,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: false,
    features: [
      { title: 'Gentle Root Removal', description: 'Preserves surrounding bone tissue for future restoration.' },
      { title: 'Infection Elimination', description: 'Removes chronic apical infection sources.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Root Removal', description: 'Precision removal of root fragment.', duration: '30 Mins' },
    ],
    benefits: ['Eliminates hidden infection', 'Prepares jaw for implants', 'Pain-free extraction'],
  },
  {
    id: 'tooth-extraction',
    slug: 'tooth-extraction',
    title: 'Tooth Extraction',
    category: 'ORAL & MAXILLOFACIAL SURGERY',
    shortDescription: 'Painless tooth extraction for non-restorable or severely decayed teeth.',
    fullDescription: 'Routine extraction of damaged or severely decayed teeth performed gently under local anesthesia with comprehensive post-op care.',
    startingPrice: 500,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: false,
    features: [
      { title: 'Painless Anesthesia', description: 'Ensures zero pain during extraction.' },
      { title: 'Socket Preservation', description: 'Optional socket preservation grafting.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Gentle Extraction', description: 'Atraumatic tooth removal.', duration: '30 Mins' },
    ],
    benefits: ['Painless procedure', 'Removes source of toothache', 'Fast healing'],
  },
  {
    id: 'oral-cancer-treatment',
    slug: 'oral-cancer-treatment',
    title: 'Oral Cancer Treatment',
    category: 'ORAL & MAXILLOFACIAL SURGERY',
    shortDescription: 'Early diagnostic screening, biopsy, and multidisciplinary oral lesion management.',
    fullDescription: 'Comprehensive screening, biopsy diagnostic evaluation, and surgical management of oral mucosal lesions and precancerous conditions.',
    startingPrice: 3000,
    durationMinutes: 60,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: false,
    features: [
      { title: 'Early Lesion Detection', description: 'Identifies mucosal dysplasia at early treatable stages.' },
      { title: 'Diagnostic Biopsy', description: 'Histopathological evaluation of oral tissue.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Clinical Examination', description: 'Mucosal screening and biopsy mapping.', duration: '30 Mins' },
      { stepNumber: 2, title: 'Surgical Management', description: 'Excision and multidisciplinary care plan.', duration: '60 Mins' },
    ],
    benefits: ['Early detection saves lives', 'Expert clinical screening', 'Comprehensive management'],
  },

  // CATEGORY 6: PEDIATRIC DENTISTRY
  {
    id: 'pulpotomy-pulpectomy',
    slug: 'pulpotomy-pulpectomy',
    title: 'Pulpotomy & Pulpectomy',
    category: 'PEDIATRIC DENTISTRY',
    shortDescription: 'Gentle pediatric root canal therapy saving infected primary milk teeth.',
    fullDescription: 'Specialized pediatric nerve treatments designed to treat infected pulp in primary teeth, preserving space for permanent adult teeth.',
    startingPrice: 600,
    durationMinutes: 40,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smile',
    popular: true,
    features: [
      { title: 'Gentle Pediatric Care', description: 'Stress-free environment tailored specifically for children.' },
      { title: 'Preserves Milk Teeth', description: 'Maintains arch length and space for permanent teeth.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Nerve Dressing', description: 'Removal of infected coronal pulp and bio-compatible dressing.', duration: '40 Mins' },
    ],
    benefits: ['Relieves children toothache', 'Preserves primary tooth space', 'Gentle child-friendly care'],
  },
  {
    id: 'habit-breaking-appliances',
    slug: 'habit-breaking-appliances',
    title: 'Habit Breaking Appliances',
    category: 'PEDIATRIC DENTISTRY',
    shortDescription: 'Custom appliances stopping thumb sucking, mouth breathing, and tongue thrusting.',
    fullDescription: 'Custom pediatric appliances designed to gently correct habits like thumb sucking, tongue thrusting, and mouth breathing before permanent jaw deformity occurs.',
    startingPrice: 1200,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smile',
    popular: false,
    features: [
      { title: 'Custom Comfort Design', description: 'Smooth appliance child can wear comfortably.' },
      { title: 'Prevents Open Bites', description: 'Protects upper arch development.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Appliance Fitting', description: 'Insertion and habit breaking counseling.', duration: '30 Mins' },
    ],
    benefits: ['Prevents crooked teeth', 'Stops thumb sucking', 'Guides natural jaw growth'],
  },
  {
    id: 'deciduous-tooth-extraction',
    slug: 'deciduous-tooth-extraction',
    title: 'Deciduous Tooth Extraction',
    category: 'PEDIATRIC DENTISTRY',
    shortDescription: 'Pain-free extraction of retained or severely decayed primary milk teeth.',
    fullDescription: 'Gentle extraction of over-retained or decayed primary teeth to allow normal eruption of permanent adult teeth.',
    startingPrice: 300,
    durationMinutes: 20,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smile',
    popular: false,
    features: [
      { title: 'Gentle Topical Numbing', description: 'Pain-free application before extraction.' },
      { title: 'Permanent Eruption Assistance', description: 'Frees space for blocking permanent teeth.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Pain-free Extraction', description: 'Quick, gentle removal of milk tooth.', duration: '20 Mins' },
    ],
    benefits: ['Painless for children', 'Allows permanent teeth to erupt', 'Fast recovery'],
  },
  {
    id: 'pit-fissure-sealants',
    slug: 'pit-fissure-sealants',
    title: 'Pit & Fissure Sealants',
    category: 'PEDIATRIC DENTISTRY',
    shortDescription: 'Protective resin coatings sealing deep molar grooves to prevent cavities.',
    fullDescription: 'Preventive resin coatings applied to deep grooves of children permanent molars, locking out bacteria and preventing cavity formation.',
    startingPrice: 250,
    durationMinutes: 20,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smile',
    popular: false,
    features: [
      { title: 'Zero Drilling', description: 'Non-invasive preventive painting technique.' },
      { title: 'Long-term Cavity Shield', description: 'Protects molars during crucial cavity-prone childhood years.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Sealant Painting', description: 'Cleaning grooves and light curing clear sealant.', duration: '20 Mins' },
    ],
    benefits: ['100% painless zero drilling', 'Prevents molar cavities', 'Quick application'],
  },

  // CATEGORY 7: ADVANCED GUM TREATMENT
  {
    id: 'cleaning-polishing',
    slug: 'cleaning-polishing',
    title: 'Cleaning & Polishing',
    category: 'ADVANCED GUM TREATMENT',
    shortDescription: 'Ultrasonic dental scaling and air-polishing for healthy gums and clean teeth.',
    fullDescription: 'Ultrasonic removal of tartar, plaque, and stubborn surface stains followed by micro-polishing for fresh breath and pink healthy gums.',
    startingPrice: 400,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    popular: true,
    features: [
      { title: 'Ultrasonic Scaling', description: 'Gently dislodges hardened calculus without scratching enamel.' },
      { title: 'Stain Air-Polishing', description: 'Removes coffee, tea, and tobacco stains.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Ultrasonic Cleaning', description: 'Removal of calculus deposits.', duration: '20 Mins' },
      { stepNumber: 2, title: 'Fluoride Polish', description: 'Polishing enamel surfaces.', duration: '10 Mins' },
    ],
    benefits: ['Freshens breath', 'Prevents gum disease', 'Removes stubborn stains'],
  },
  {
    id: 'teeth-whitening-bleaching',
    slug: 'teeth-whitening-bleaching',
    title: 'Teeth Whitening / Bleaching',
    category: 'ADVANCED GUM TREATMENT',
    shortDescription: 'Clinical laser teeth whitening brightening teeth by up to 8 shades in 1 hour.',
    fullDescription: 'In-office laser-assisted dental whitening therapy removing deep enamel stains and brightening your natural smile up to 8 shades in 1 session.',
    startingPrice: 1200,
    durationMinutes: 60,
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    popular: true,
    features: [
      { title: 'In-Office Laser Light', description: 'Accelerated clinical formula for instant results.' },
      { title: 'Desensitizing Gel Included', description: 'Ensures comfortable treatment without tooth sensitivity.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Gum Barrier Application', description: 'Protecting gums with light-cured barrier.', duration: '15 Mins' },
      { stepNumber: 2, title: 'Laser Activation', description: 'Three 15-minute whitening cycles.', duration: '45 Mins' },
    ],
    benefits: ['Up to 8 shades whiter', 'Completed in 60 mins', 'Safe enamel protection'],
  },
  {
    id: 'bleeding-gum-treatment',
    slug: 'bleeding-gum-treatment',
    title: 'Bleeding Gum Treatment',
    category: 'ADVANCED GUM TREATMENT',
    shortDescription: 'Deep periodontal scaling and curettage eliminating gum infection and bleeding.',
    fullDescription: 'Targeted periodontal therapy including subgingival scaling, root planing, and antimicrobial irrigation to stop bleeding gums and treat gingivitis.',
    startingPrice: 800,
    durationMinutes: 45,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'Deep Root Planing', description: 'Smoothes root surfaces to allow gum tissue reattachment.' },
      { title: 'Antimicrobial Wash', description: 'Flushes bacterial pockets to halt bleeding.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Deep Subgingival Cleaning', description: 'Cleaning deep gum pockets.', duration: '45 Mins' },
    ],
    benefits: ['Stops gum bleeding', 'Tightens loose gums', 'Prevents tooth loss'],
  },
  {
    id: 'bad-breath-treatment',
    slug: 'bad-breath-treatment',
    title: 'Bad Breath Treatment',
    category: 'ADVANCED GUM TREATMENT',
    shortDescription: 'Comprehensive halitosis diagnosis and targeted oral bacteria therapy.',
    fullDescription: 'Clinical evaluation identifying underlying causes of chronic halitosis (bad breath) followed by deep tongue cleaning and periodontal pocket disinfection.',
    startingPrice: 500,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    popular: false,
    features: [
      { title: 'Halitosis Screening', description: 'Pinpoints exact bacterial breeding pockets.' },
      { title: 'Tongue & Pocket Debridement', description: 'Eliminates sulfur-producing bacterial colonies.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Clinical Debridement', description: 'Targeted bacterial removal and rinse.', duration: '30 Mins' },
    ],
    benefits: ['Long-lasting fresh breath', 'Eliminates bacterial origin', 'Restores oral confidence'],
  },
  {
    id: 'splinting',
    slug: 'splinting',
    title: 'Splinting',
    category: 'ADVANCED GUM TREATMENT',
    shortDescription: 'Periodontal wire and fiber splinting stabilizing loose or traumatized teeth.',
    fullDescription: 'Composite fiber or wire splinting bonding loose periodontally-compromised teeth together to share biting forces and promote bone healing.',
    startingPrice: 700,
    durationMinutes: 45,
    heroImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: false,
    features: [
      { title: 'Stabilizes Loose Teeth', description: 'Joins mobile teeth to adjacent firm teeth.' },
      { title: 'Esthetic Fiber Ribbons', description: 'Concealed composite fiber splints behind teeth.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Fiber Splint Bonding', description: 'Bonding high-strength fiber ribbon.', duration: '45 Mins' },
    ],
    benefits: ['Saves loose teeth', 'Prevents extraction', 'Comfortable biting'],
  },

  // CATEGORY 8: ORAL MEDICINE & RADIOLOGY
  {
    id: 'digital-x-ray',
    slug: 'digital-x-ray',
    title: 'Digital X-Ray',
    category: 'ORAL MEDICINE & RADIOLOGY',
    shortDescription: 'Low-radiation instant RVG digital intraoral radiography.',
    fullDescription: 'Instant high-resolution digital X-rays (RVG) with up to 90% less radiation exposure than conventional film X-rays.',
    startingPrice: 150,
    durationMinutes: 10,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: '90% Radiation Reduction', description: 'Ultra-low radiation exposure.' },
      { title: 'Instant Screen Display', description: 'Immediate diagnosis on chairside monitors.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Digital Radiograph', description: 'Sensor placement and instant exposure.', duration: '10 Mins' },
    ],
    benefits: ['Instant 1-second result', 'Ultra low radiation', 'High resolution accuracy'],
  },
  {
    id: 'tobacco-cessation',
    slug: 'tobacco-cessation',
    title: 'Tobacco Cessation',
    category: 'ORAL MEDICINE & RADIOLOGY',
    shortDescription: 'Clinical counseling, mucosal health screening, and tobacco de-addiction guidance.',
    fullDescription: 'Professional clinical counseling, nicotine replacement therapy guidance, and oral mucosal monitoring to help patients quit tobacco.',
    startingPrice: 400,
    durationMinutes: 30,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: false,
    features: [
      { title: 'Mucosal Mapping', description: 'Monitors tobacco-related tissue changes.' },
      { title: 'De-Addiction Protocol', description: 'Structured clinical guidance to quit smoking/chewing.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Counseling & Screening', description: 'Evaluation and customized cessation plan.', duration: '30 Mins' },
    ],
    benefits: ['Protects oral health', 'Prevents oral precancer', 'Professional support'],
  },
  {
    id: 'opg-cbct',
    slug: 'opg-cbct',
    title: 'OPG/CBCT',
    category: 'ORAL MEDICINE & RADIOLOGY',
    shortDescription: 'Full-mouth panoramic OPG X-ray and 3D Cone Beam Computed Tomography (CBCT).',
    fullDescription: 'Comprehensive 3D CBCT bone scans and full-jaw panoramic OPG radiographs for implant planning, wisdom teeth mapping, and joint evaluation.',
    startingPrice: 1500,
    durationMinutes: 15,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: '3D Bone Density Volume', description: 'Sub-millimeter 3D cross-sectional jaw views.' },
      { title: 'Nerve Path Tracing', description: 'Maps inferior alveolar nerve and maxillary sinuses.' },
    ],
    processSteps: [
      { stepNumber: 1, title: '3D Scan Acquisition', description: '15-second non-contact panoramic scan.', duration: '15 Mins' },
    ],
    benefits: ['3D sub-millimeter precision', 'Essential for implant planning', 'Fast non-contact scan'],
  },
  {
    id: '3d-scanning',
    slug: '3d-scanning',
    title: '3D-Scanning',
    category: 'ORAL MEDICINE & RADIOLOGY',
    shortDescription: 'Impression-free intraoral 3D digital optical scanning.',
    fullDescription: 'Impression-free 3D digital intraoral optical scanning replacing messy alginate impressions with instant, accurate 3D digital dental models.',
    startingPrice: 800,
    durationMinutes: 15,
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop',
    iconName: 'ShieldCheck',
    popular: true,
    features: [
      { title: 'No Messy Goo', description: 'Replaces uncomfortable impression trays with a digital wand.' },
      { title: 'Instant 3D Simulation', description: 'View your 3D smile on screen immediately.' },
    ],
    processSteps: [
      { stepNumber: 1, title: 'Intraoral Scan', description: 'Optical scan of upper and lower arches.', duration: '15 Mins' },
    ],
    benefits: ['Zero gagging or messy trays', 'Instant 3D digital result', 'Sub-millimeter accuracy'],
  },
];
